FROM hashicorp/terraform:1.2.3

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0.0"
LABEL description "Terraform: 1.2.3, gnupg, jq"

RUN apk add --no-cache gnupg jq

CMD ["/bin/bash"]

