FROM debian:buster-slim

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="v0.3.19"
LABEL description "vim-vint: 0.3.19"

RUN apt-get update && apt-get -y install \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -U vim-vint

