FROM node:18

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="20220603"
LABEL description "generator-langium, node:18"

RUN npm i -g yo generator-langium

USER node
WORKDIR /home/node
CMD bash
