FROM debian:stretch-slim

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="2.02-4+b2"
LABEL description "version: 2.02-4+b2"

RUN apt-get update && apt-get install -y \
    pdftk=2.02-4+b2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD /bin/bash

