# コンテナとして使う環境を作る
FROM mikoto2000/toppers-kernel-build-kit:base-latest

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0.0"
LABEL description "toppers-kernel-build-kit. gcc-aarch64-linux-gnu: 4:8.3.0-1"

# aarch64 用のバイナリビルドができる環境を構築
RUN apt-get update && apt-get -y install \
    gcc-aarch64-linux-gnu=4:8.3.0-1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

