# ビルド環境を構築してビルド
FROM debian:buster-slim as build-env

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0.0"
LABEL description "toppers-kernel-build-kit. gcc-arm-none-eabi: 15:7-2018-q2-6"

RUN apt-get update \
    && apt-get -y install curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# cfg
RUN curl -L -O https://github.com/mitsut/cfg/releases/download/1.9.7/cfg-1.9.7-x86_64-unknown-linux-gnu.tar.gz \
    && tar xf cfg-1.9.7-x86_64-unknown-linux-gnu.tar.gz \
    && mv cfg /usr/local/bin/cfg \
    && rm cfg-1.9.7-x86_64-unknown-linux-gnu.tar.gz
# コンテナとして使う環境を作る
FROM mikoto2000/toppers-kernel-build-kit:base-latest

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0.0"
LABEL description "toppers-kernel-build-kit. gcc-arm-none-eabi: 15:7-2018-q2-6"

RUN apt-get update && apt-get -y install \
    gcc-arm-none-eabi=15:7-2018-q2-6 \
    perl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build-env \
    /usr/local/bin/cfg \
    /usr/local/bin/cfg
