# イメージビルド環境
FROM debian:buster-slim AS build-env

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0.0"
LABEL description "toppers-kernel-build-kit. zig: 0.6.0+4e63cae36, gcc-arm-none-eabi: 15:7-2018-q2-6"

RUN apt-get update && apt-get -y install \
    curl xz-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# zig 0.6.0+4e63cae36 を /opt/zig-linux-x86_64-0.6.0+4e63cae36 にインストール
RUN curl -L https://ziglang.org/builds/zig-linux-x86_64-0.6.0+4e63cae36.tar.xz -O \
    && tar xf zig-linux-x86_64-0.6.0+4e63cae36.tar.xz -C /opt \
    && rm zig-linux-x86_64-0.6.0+4e63cae36.tar.xz

# tecsgen 1.7.0 のインストール
RUN curl -L https://www.toppers.jp/download.cgi/tecsgen-1.7.0.tgz -O \
    && tar xf tecsgen-1.7.0.tgz -C /opt \
    && rm tecsgen-1.7.0.tgz


# コンテナとして使う環境を作る
FROM mikoto2000/toppers-kernel-build-kit:gcc-arm-none-eabi-latest

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="1.0.0"
LABEL description "toppers-kernel-build-kit. zig: 0.6.0+4e63cae36, gcc-arm-none-eabi: 15:7-2018-q2-6"

COPY --chown=root:root --from=build-env \
    /opt/zig-linux-x86_64-0.6.0+4e63cae36 /opt/zig-linux-x86_64-0.6.0+4e63cae36

COPY --chown=root:root --from=build-env \
    /opt/tecsgen-1.7.0 /opt/tecsgen-1.7.0

RUN chmod 755 /opt/tecsgen-1.7.0/tecsgen \
    && find /opt/tecsgen-1.7.0/tecsgen -type d -print0 | xargs -0 chmod 755 \
    && find /opt/tecsgen-1.7.0/tecsgen -type f -name '*.rb' -print0 | xargs -0 chmod 755

ENV PATH=$PATH:/opt/zig-linux-x86_64-0.6.0+4e63cae36

