FROM debian:buster-slim

LABEL maintainer "mikoto2000 <mikoto2000@gmail.com>"
LABEL version="v1.8.4"
LABEL description "sphinx: 1.8.4"

RUN apt-get update && apt-get -y install \
    python3-pip \
    locales \
    locales-all \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# sphinx 環境構築
RUN pip3 install -U sphinx

# 日本語パス対応
ENV LANG=ja_JP.UTF-8


